### PR TITLE
Use new TravisCI infrastructure

### PR DESCRIPTION
**Pull request by tgalopin**
Because, you know, containers, speed and stuff :) .

### CODE REVIEW

**Comment by webmozart** [comment]
Thanks! :) What's the effect of sudo false?

**Comment by tgalopin** [comment]
It just uses the new Travis CI architecture which is faster and recommended :) .

**Comment by xabbuh** [comment]
@webmozart http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by webmozart** [comment]
Just found it on Google, thanks :)

**Pull request merged**
