### PR TITLE
[READY] Fix ScrunitizerCI and SensioLabs Insights issues

### PR DESCRIPTION
**Pull request by tgalopin**
Try to fix the issues of:

- https://scrutinizer-ci.com/g/webmozart/key-value-store/issues/master
- https://insight.sensiolabs.com/projects/61586798-236a-462a-8429-d8311c1a2500

### CODE REVIEW

**Comment by webmozart** [comment]
Woa awesome, thanks! :) Could you fix the remaining CS issues?

**Comment by webmozart** [comment]
I realized that many CS issues were there before your PR. I fixed them now, could you rebase your PR onto master?

**Comment by tgalopin** [comment]
I will tomorrow :)

**Comment by tgalopin** [comment]
I love ScrunitizerCI messages :smile::

> Uh, seems like someone is on fire. 49 issues were fixed!

Other than that, I think it's ready. There still are some false-positives issues about code dupplication but I think it's not really a problem (it's not real code duplication).

This issue is a real one: https://scrutinizer-ci.com/g/webmozart/key-value-store/inspections/afcd1173-3392-4e13-a0cb-266666ea8334/issues/files/src/RiakStore.php?status=existing&selectedLabels%5B0%5D=7&orderField=path&order=asc

But it's a problem in the Riak library, they should put mixed instead of object. I'll write a small PR :) .

**Comment by webmozart** [comment]
Yes, saw that too :) Could you apply the StyleCI patch and squash your commits?

In case you don't know what I mean: Find the commit *before* your first commit (e.g. with hash `abcd`). Then do:

```
$ git rebase -i abcd
```

This will present you with all your commits. Leave the "pick" in front of the first commit and replace the "pick" of all subsequent commits with "s" (or "squash"). This way those commits will be merged into the first one.

You'll need to do `git push -f` to update the PR.

**Comment by tgalopin** [comment]
I think we should wait for https://github.com/webmozart/key-value-store/pull/9 to be merged before finalizing this PR as I'm not sure about the conflicts.

**Comment by webmozart** [comment]
Merged now ;)

**Comment by tgalopin** [comment]
Still the `@return void` problem, but the rest seems ready.

**Comment by webmozart** [comment]
Cool, thanks :) I filtered that issue on Scrutinizer now.

**Comment by tgalopin** [comment]
https://insight.sensiolabs.com/projects/61586798-236a-462a-8429-d8311c1a2500/analyses/61 :)

**Comment by webmozart** [comment]
\o/ congrats! :)

**Pull request merged**
